### PR TITLE
Add RubyConf TH videos

### PR DESCRIPTION
**Pull request by marcoroth**
CleanShot 2024-08-09 at 20 06 08

### CODE REVIEW

**Comment by adrienpoly** [comment]
Could you update the published_at date with the first day of the conference. This is what I am using for sorting the talks by dates. YouTube published date is only an approximation. Good enough if we don’t have the real date

**Comment by marcoroth** [comment]
Updated, maybe we should rename that field then.  I understood `published_at` as "the date the video was published on", but something like `date` would probably be more accurate. 

I updated the dates to be exact to the respective day of the conference.

**Comment by adrienpoly** [comment]
Great yeah I agree it is confusing 

maybe the date field could be optional if we have it we take it if not then we fallback to the published_at. This way we don’t have to update all existing files

**Comment by marcoroth** [comment]
I'm happy to backfill them if we agree on something 🙌🏼

**Pull request merged**
