### PR TITLE
Add content from RubyConf AU 2023

### PR DESCRIPTION
**Pull request by Cueball**
CleanShot 2024-10-24 at 00 51 09

### CODE REVIEW

**Comment by Cueball** [comment]
"If there are any issues or uncertainties, feel free to raise them during the PR process."

Deliberately didn't clone the app - just made changes to relevant yaml files. Really not sure if this is going to work...

**Comment by adrienpoly** [comment]
thanks will test it over the weekend and also try to provide better tooling to create the data/files #25

**Comment by marcoroth** [comment]
I think this PR looks actually good too. Is there anything missing from your side @adrienpoly?

**Review by marcoroth — APPROVED** [review]
Thank you @Cueball! 🙌🏼

**Pull request merged**
