### PR TITLE
Add `slides_url` to `Talk` model and embed slides from speakerdeck.com

### LINKED ISSUE #153: Add `slides_url` to `Talk` model
I noticed that some of the talks have an URL to the slides in the description. Maybe we can add that to the `Talk` model and link/embed them in a nice way next to the video.

For the Ruby Unconf talks (#114) I added a `slides_url` field to the YAML files where I had it available.

### PR DESCRIPTION
**Pull request by marcoroth**
This pull request adds the `slides_url` to the `Talk` model and also adds a new tab to the talk show page if the talk has a `slides_url` associated with it.

CleanShot 2024-08-24 at 00 23 18

If the slides are hosted on speakerdeck.com we can embed the slides using the player they provide (thanks @jnunemaker for the tip, see [docs](https://help.speakerdeck.com/help/how-do-i-use-oembed-to-display-a-deck-on-my-site))

CleanShot 2024-10-16 at 17 20 53@2x

Closes #153

### CODE REVIEW

**Comment by marcoroth** [comment]
@adrienpoly this should be ready now 🙌🏼

**Comment by adrienpoly** [comment]
great 

will deploy it to prod a bit later and ping you

**Comment by marcoroth** [comment]
Thanks! You might need to run `update_from_yml_metadata!` so it writes the `slides_url` to the database

**Comment by adrienpoly** [comment]
@marcoroth https://www.rubyvideo.dev/talks/take-your-slow-tests-to-the-doctor?back_to=%2Ftalks%3Fq%3Dslow%2Btest%2Bdoc

thanks for this

**Comment by marcoroth** [comment]
Awesome, nice! 

/cc @palkan ☝🏼

**Pull request merged**
