### PR TITLE
Show a few speakers

### LINKED ISSUE #10: Fix the card when they are lots of speakers
On the card we should only display a few speakers to prevent such layout

CleanShot 2023-06-17 at 07 31 11@2x

### PR DESCRIPTION
**Pull request by enderahmetyurt**
Screenshot 2023-06-24 at 08 55 11

Close #10

### CODE REVIEW

**Comment by marcoroth** [comment]
This looks great! 

I think it would be even nicer if it would show the first 2/3 speakers and additionally say "and 10 more" if there are any speakers remaining.

**Comment by enderahmetyurt** [comment]
how does it look now @marcoroth

**Comment by marcoroth** [comment]
Thank you, @enderahmetyurt! 

I was wondering if 10 people are not a bit too much, but this looks great to me otherwise!

**Comment by enderahmetyurt** [comment]
> Thank you, @enderahmetyurt!
> 
> I was wondering if 10 people are not a bit too much, but this looks great to me otherwise!

you might be right. 5 would be enough.

**Comment by enderahmetyurt** [comment]
@adrienpoly what do you think about it?

**Comment by adrienpoly** [comment]
hello thanks for your proposal

I would prefer that we use most of the available space on the lines

here is a quick draft
CleanShot 2023-07-08 at 11 58 50@2x

```erb
            <strong class="mt-5">Speakers:</strong>
            <div class="line-clamp-2">
              <% talk.speakers.shuffle.each do |speaker| %>
                <%= link_to speaker.name, speaker_path(speaker), class: "whitespace-nowrap" %>
              <% end %>
            </div>
```

with comas in between that would be perfect

**Comment by adrienpoly** [comment]
Thanks for your investigation on that one I did some follow up in #44 as I couldn't add commits to this branch.

**Pull request closed without merging**
