### PR TITLE
Fix back navigation

### PR DESCRIPTION
**Pull request by Ukaypromise**
### Hello 👋🏽 @adrienpoly ,
I believe a better and easy way would be to use `:back`

The :back option in Ruby on Rails provides a convenient way to navigate back to the previous page. It automatically generates the appropriate URL based on the HTTP referer header.

Using :back can be a good option in many cases, especially when you want to implement a generic back button that takes the user back to wherever they came from. It simplifies the code and handles the navigation automatically.

### CODE REVIEW

**Comment by adrienpoly** [comment]
Thanks that is an interesting approach. My only concern is when we would arrive from a Google search result then it would take us bac to this search result. Is there a way to provide a fallback?

**Comment by Ukaypromise** [comment]
Okay I get it now. Just give me today, I will fix it properly @adrienpoly

**Comment by Ukaypromise** [comment]
@adrienpoly Made some modifications.

**Comment by adrienpoly** [comment]
Thanks, it does not cover the search results let's say I search for Aaron and visit a show and then come back I won't have the same results but it remains improvements. I'll probably open an issue to improve that further down the road once the search has been stabilized

**Pull request merged**
