### PR TITLE
Add RubyNation 2017 videos

### PR DESCRIPTION
**Pull request by marcoroth**
CleanShot 2024-10-23 at 15 04 32

### CODE REVIEW

**Comment by adrienpoly** [comment]
spent a bit of time investigating the test failure. It was I think a wrong format for published at

**Comment by marcoroth** [comment]
Oh wow, I looked at this before and couln't figure out what's wrong. 

Looking at the diff I don't see it either now, but doesn't matter - but great it's working now! 🙌🏼

Thank you!

**Comment by adrienpoly** [comment]
Yeah diff is more complex Than it should be. Tried a lot of things before finding 


They were one 
  published_at: "2017" with only the year

**Comment by marcoroth** [comment]
ah I see, thanks! 🙌🏼

**Pull request merged**
